### PR TITLE
Overall updates and junk removal

### PR DESCRIPTION
**Pull request by boredland**
The current highlights are:
- Fontawesome instead of images whereever possible.
- Deciding between local and cdn-loading
- Hyphens
- Integration of the current grav forms
- Update libraries
- Readd gmaps integration
- Make a lot of options "on page"-options and update the demo accordingly.

### CODE REVIEW

**Comment by boredland** [comment]
The demo is updated and ready to try. The TODOs were updated, but I think this is only a matter of time.

**Comment by Sommerregen** [comment]
You did a really great job! I really like the `cdn` toggle option and your overall re-factoring. Of course your TODOs are also nice to have at least to replace the theme-contact-options with page-options, just let me know when you are ready :-).

One thing that will be open for improvement: updating the theme blueprint. Currently, it is just a stub. If you like you can do it, otherwise I will do it after merging your changes.

**Comment by boredland** [comment]
I readded a working gmaps-integration, sadly theres a little regarding the name of the grav-google-maps plugin, but I created a PR already. All settings moved to their pages already.

**Comment by boredland** [comment]
Updated the readme. I think you could merge and update the blueprint.

**Comment by boredland** [comment]
Looks like the mantainer oft the google-maps isn't willing to comply his config-path with twig. I'll add the option to set the api-key in the theme-settings.

**Comment by Sommerregen** [comment]
Ok, I will wait. what we can also do is to integrate the gmaps plugin into the theme. A theme is also only a "plugin".

**Comment by boredland** [comment]
I just added a key to the template. I think thats the easiest way. If you don't have other remarks I think you could merge.

**Comment by Sommerregen** [comment]
Well done! I will look into it shortly, because I'm almost on vacation for approx. two weeks. Will review and merge this soon and add things, when something is still missing. I'll let you know.

See you.

**Comment by Sommerregen** [comment]
Dear @boredland ,

I finally reviewed your additions and merged your changes in the develop branch. Furthermore, I adjusted the theme and your configurations:

- The theme shows the language switcher block only if the plugin is actually installed
- Google Maps are only shown, if the google maps plugin is installed and enabled (provided a given google api key was set there, of course)
- I further fixed a bug with the hyphenate JS (now the language is set correctly)

Please tell me what you think. Otherwise I will release a new version.

**Comment by boredland** [comment]
Awesome!

**Comment by Sommerregen** [comment]
Ok, it's released 🎉 Big thanks again!

**Pull request merged**
